### ISSUE TITLE
Ansible systemd config is not working

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops-arm#8]
The following doesn't get applied for some reason...

```
- name: Start and enable timesyncd
  systemd:
    name: systemd-timesyncd
    state: started
    enabled: true
```
